### ISSUE TITLE
jsonsl_util_unescape() rejects encoded NULL bytes: "\u0000"

### ISSUE THREAD

**Issue by ajdavis** [mnunberg/jsonsl#21]
I think this is valid JSON encoding for a value containing NULL:

`{"key": "a\u0000b"}`

The Python standard `json` codec can produce and consume such strings. But jsonsl_util_unescape deliberately rejects such strings:

        uescval = jsonsl__get_uescape_16((const char *)c + 2);
        if (uescval == -1) {
            UNESCAPE_BAIL(PERCENT_BADHEX, -1);
        } else if (uescval == 0) {
            UNESCAPE_BAIL(INVALID_CODEPOINT, 2);
        }

Why is this? I propose that "\u0000" be considered a valid escape sequence, and encoded into the UTF-8 output string as a zero.

**Comment by ajdavis** [comment]
Would you like a pull request for this issue, allowing "\u0000" to be parsed as a NIL embedded in the string? I propose to make it the new default behavior of JSONSL, since [the JSON spec RFC 7159](https://tools.ietf.org/html/rfc7159) in the "Strings" section requires it:

>    Any character may be escaped.  If the character is in the Basic
>    Multilingual Plane (U+0000 through U+FFFF), then it may be
>    represented as a six-character sequence: a reverse solidus, followed
>    by the lowercase letter u, followed by four hexadecimal digits that
>    encode the character's code point.

**Comment by mnunberg** [comment]
It seems that NULL is indeed an allowable value. Fixed.

**Comment by ajdavis** [comment]
Thanks!
