### ISSUE TITLE
Parse "NaN"

### ISSUE THREAD

**Issue by ajdavis** [mnunberg/jsonsl#24]
Python's JSON parser and others understand:
```
{"x": NaN}
```
I can offer a pull request for JSONSL to understand it too, if you're interested.

**Comment by mnunberg** [comment]
I'm not opposed to it in principle.. I guess it can be offered as a compile time option, rather than enabling it at runtime (esp. for negative validation?).

On the topic of Python, I've been meaning to make an extension for jsonsl for quite a while now...
