### ISSUE TITLE
OBJECT size ambiguity

### ISSUE THREAD

**Issue by Murf-Perftech** [mnunberg/jsonsl#39]
It appears that in the pop callback for an OBJECT, state->pos_cur is the location of  a '"' character if the object ends with a STRING, and the location of the '}' character otherwise, making it difficult to determine the length of the OBJECT.  Is this by design?  If so, what is the proper way to determine the length of an OBJECT?

**Comment by mnunberg** [comment]
Perhaps you can try `->pos` (in the parser itself) rather than `state->pos_cur`?

**Comment by Murf-Perftech** [comment]
Well yes, of course that works --- but fixing the bug would be
nice.

Murf

Mark Nunberg wrote:

  Perhaps you can try ->pos (in the parser itself)
rather than state->pos_cur?
  —
You are receiving this because you authored the thread.
Reply to this email directly, view
it on GitHub, or mute
the thread.
  
  
  
  
  
  
  
  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mnunberg/jsonsl","title":"mnunberg/jsonsl","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/mnunberg/jsonsl">"https://github.com/mnunberg/jsonsl"</a>}},"updates":{"snippets":[{"icon":"PERSON","
message":"@mnunberg in #39: Perhaps you can try `-\u003epos` (in the parser itself) rather than `state-\u003epos_cur`?"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/mnunberg/jsonsl/issues/39#issuecomment-341561147">"https://github.com/mnunberg/jsonsl/issues/39#issuecomment-341561147"</a>}}}

**Comment by mnunberg** [comment]
In the comments I've marked `pos_cur` as deprecated for this reason (among others). I don't want to break people's APIs though...

**Comment by Murf-Perftech** [comment]
Boy do I understand not wanting to break stuff!  Fixing the
documentation is as good as fixing the bug --- in some ways, even
better:)

Thanks!

Murf

Mark Nunberg wrote:

  In the comments I've marked pos_cur as deprecated
for this reason (among others). I don't want to break people's APIs
though...
  —
You are receiving this because you authored the thread.
Reply to this email directly, view
it on GitHub, or mute
the thread.
  
  
  
  
  
  
  
  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mnunberg/jsonsl","title":"mnunberg/jsonsl","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/mnunberg/jsonsl">"https://github.com/mnunberg/jsonsl"</a>}},"updates":{"snippets":[{"icon":"PERSON","
message":"@mnunberg in #39: In the comments I've marked `pos_cur` as deprecated for this reason (among others). I don't want to break people's APIs though..."}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/mnunberg/jsonsl/issues/39#issuecomment-341681795">"https://github.com/mnunberg/jsonsl/issues/39#issuecomment-341681795"</a>}}}

**Comment by mnunberg** [comment]
Fixed in docs.
