### ISSUE TITLE
No info about state of codebase

### ISSUE THREAD

**Issue by borrrden** [mnunberg/jsonsl#40]
Does jsonsl have the concept of releases, or development vs production?  I want to know if it is safe to always grab the latest commit in master to use in production (in other words, there is no other method to tell if any commit is "better" than another such as release tags, etc).

**Comment by mnunberg** [comment]
It should be generally safe to grab the latest version; but I’d recommend that you evaluate upgrading for performance etc.

**Comment by borrrden** [comment]
Thanks for the response!
