### ISSUE TITLE
Incorrect unescaping of \u sequences in jsonsl_util_unescape_ex

### ISSUE THREAD

**Issue by snej** [mnunberg/jsonsl#9]
After jsonsl_util_unescape_ex parses a `\uxxxx` escape, where `xxxx` is a hex number greater than FF, it simply writes the number as two 8-bit bytes. This isn't correct in any character encoding and will result in either garbage characters, or a decoding failure.

For example, the escape `\u20ac` (a Euro symbol) would be written as the bytes 0x20 0xAC, i.e a space character followed by some non-ASCII character whose interpretation depends on the encoding. A UTF-8 decoder would barf on this because it's illegal for 0xAC to follow an ASCII character.

The correct behavior depends on what encoding the output should have. Basically the decoded hex number needs to be interpreted as a Unicode code point between U-0000 and U-FFFF, and converted to that encoding. 

Since the API doesn't specify an encoding, it makes sense to default to UTF-8. Converting to UTF-8 [isn't that hard](https://en.wikipedia.org/wiki/UTF-8#Description), just some bit-shifting and masking.

**Comment by mnunberg** [comment]
I could probably add that logic in there! thanks for reporting

**Comment by snej** [comment]
I'm currently writing it myself, but as a separate function. It's in C though, so I could send you the code to incorporate...

**Comment by snej** [comment]
Here's my (tested) code. It's actually C++, but the only thing you'd need to change is the reference parameter.
```c++
    // similar to BSD digittoint, but returns -1 on failure
    static int digit2int(char ch) {
        int d = ch - '0';
        if ((unsigned) d < 10) {
            return d;
        }
        d = ch - 'a';
        if ((unsigned) d < 6) {
            return d + 10;
        }
        d = ch - 'A';
        if ((unsigned) d < 6) {
            return d + 10;
        }
        return -1;
    }

    // Writes a Unicode code point from 0000 to FFFF as a UTF-8 byte sequence
    static void writeUTF8(uint8_t* &dst, unsigned u) {
        // https://en.wikipedia.org/wiki/UTF-8#Description
        if (u < 0x0080) {
            *dst++ = (uint8_t)u;
        } else if (u < 0x0800) {
            *dst++ = (uint8_t)(0xC0 | (u >> 6));
            *dst++ = (uint8_t)(0x80 | (u & 0x3F));
        } else {
            //assert(u < 0xFFFF);
            *dst++ = (uint8_t)(0xE0 | (u >> 12));
            *dst++ = (uint8_t)(0x80 | ((u >>  6) & 0x3F));
            *dst++ = (uint8_t)(0x80 | (u & 0x3F));
        }
    }

    // src points to 1st hex digit after "\u". Decoded byte(s) will be written at dst.
    static bool decodeUnicodeEscape(uint8_t* &dst, const char* src) {
        int d0 = digit2int(src[0]), d1 = digit2int(src[1]),
            d2 = digit2int(src[2]), d3 = digit2int(src[3]);
        if (d0 < 0 || d1 < 0 || d2 < 0 || d3 < 0)
            return false;
        unsigned u = (d0 << 12) | (d1 << 8) | (d2 << 4) | (d3);
        writeUTF8(dst, u);
        return true;
    }
```

**Comment by mnunberg** [comment]
I raise you https://github.com/couchbase/subjson/blob/master/subdoc/uescape.h#L143, which also handles surrogate pairs :)

**Comment by snej** [comment]
Oh yeah, surrogate pairs … _/me quickly fixes up code_

**Comment by mnunberg** [comment]
I've fixed this in a separate branch. I decided to go along with the existing uescape implementation from subjson (since I wrote that as well) though your implementation is likely quicker - so it might go in there later on.

**Comment by mnunberg** [comment]
Marking as closed since issue has been fixed in the referenced commit
